import { HEADER_CATEGORY_SLUG_ADMIN } from '.'

export const allRoutes = {
  login: '/',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  socialDashboard: '/social-dashboard',
  roles: '/settings/roles',
  roleAdd: '/settings/roles/add',
  roleEdit: (id) => `/settings/roles/edit/${id}`,
  subAdmins: '/settings/users',
  addSubAdmin: '/settings/users/add',
  editSubAdmin: (id) => `/settings/users/edit/${id}`,

  blogList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.b}/${type}`,
  webinarList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.w}/${type}`,
  podcastList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.p}/${type}`,
  whitePaperList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.wp}/${type}`,
  researchReportList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.rr}/${type}`,
  videoListingList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.vl}/${type}`,
  caseStudyList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.cs}/${type}`,
  newsAndEventList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.cu}/${type}`,
  mediaGalleryList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.mg}/${type}`,
  editPost: (type, id, slug) => `/${slug}/edit/${id}/${type}`,
  addPost: (type, slug) => `/${slug}/create/${type}`,

  headerBlogCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.b}/setting/${type}`,
  headerWebinarCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.w}/setting/${type}`,
  headerPodcastCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.p}/setting/${type}`,
  headerWhitepaperCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.wp}/setting/${type}`,
  headerResearchReportCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.rr}/setting/${type}`,
  headerVideoListingCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.vl}/setting/${type}`,
  headerCaseStudyCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.cs}/setting/${type}`,
  headerCareerCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.cy}/setting/${type}`,
  headerNewsCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.cu}/setting/${type}`,
  headerMediaGalleryCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.mg}/setting/${type}`,

  blogCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.b}/categories/${type}`,
  webinarCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.w}/categories/${type}`,
  podcastCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.p}/categories/${type}`,
  whitePaperCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.wp}/categories/${type}`,
  researchReportCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.rr}/categories/${type}`,
  videoListingCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.vl}/categories/${type}`,
  caseStudyCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.cs}/categories/${type}`,
  newsAndEventCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.cu}/categories/${type}`,
  mediaGalleryCategory: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.mg}/categories/${type}`,
  addCategory: (type, slug) => `/${slug}/categories/add/${type}`,
  editCategory: (type, id, slug) => `/${slug}/categories/edit/${id}/${type}`,

  authorsList: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.b}/authors/${type}`,
  authorsCreate: (type) => `/${HEADER_CATEGORY_SLUG_ADMIN.b}/authors/create/${type}`,
  authorsEdit: (type, id) => `/${HEADER_CATEGORY_SLUG_ADMIN.b}/authors/edit/${id}/${type}`,

  services: '/services',
  createService: '/services/create',
  servicesEdit: (id) => `/services/edit/${id}`,
  industries: '/industries',
  createIndustries: '/industries/create',
  editIndustries: (id) => `/industries/edit/${id}`,
  products: '/products',
  createProduct: '/products/create',
  editProduct: (id) => `/products/edit/${id}`,
  careers: '/careers',
  addCareer: '/careers/create',
  editCareer: (id) => `/careers/edit/${id}`,
  careerLocations: '/careers/locations',
  inquiry: '/lead-management/inquiry',
  contacts: '/lead-management/contacts',
  popupList: '/popups',
  popupAdd: '/popups/add',
  popupEdit: (id) => `/popups/edit/${id}`,

  tags: '/management/tags',
  addTag: '/management/tags/add-tag',
  editTag: (id) => `/management/tags/edit-tag/${id}`,
  manageSeo: (id) => `/management/categories/edit-category/${id}/manage-seo`,
  editProfile: '/dashboard/profile',
  seo: '/settings/seo',
  addSeo: '/settings/seo/add-seo',
  editSeo: (type, id) => `/settings/seo/${type}/${id}`,
  seoRedirects: '/settings/seo-redirects',
  jobPost: '/settings/job-post',
  detailEnquiry: (id) => `/settings/enquiry-detail/${id}`,
  addJobPost: '/settings/job-post/add-job-post',
  editJobPost: (type, id) => `/settings/job-post/${id}/${type}`,
  endUsers: '/settings/end-users',
  detailEndUser: (id) => `/settings/end-users/details/${id}`,
  cms: '/settings/cms',
  addCms: '/settings/cms/add-cms',
  editCms: (id) => `/settings/cms/edit-cms/${id}`,
  arrangeMenu: '/settings/arrange-menu',
  media: '/media-gallery',
  pageComponents: '/page-components',
  pageComponentsEdit: (type) => `/page-components/${type}`,
  testimonials: '/testimonials',
  addTestimonial: '/testimonial/add',
  editTestimonial: (id) => `/testimonials/edit/${id}`,
  listPage: '/setting/pages',
  createPage: '/setting/pages/create',
  editPage: (id, name) => `/setting/pages/${name}/${id}`,
  marquee: '/settings/marquee',
  chatBot: '/chat-bot',
  chatBotResponse: '/lead-management/chat-bot-response',
  projectConfig: '/settings/project-config'
}
